org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.14.7-hotspot
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.14.7-hotspot,C:\\Program Files\\Java\\jdk-21
